# Make_FCS_Overview_Plots.py
#
# =============================================================================
# HIGH-LEVEL OVERVIEW
# =============================================================================
# This script organises the PNG outputs generated by the FCS visualisation and
# gating modules by collating individual plots into larger overview grid images.
#
# It does NOT read .fcs files directly and does NOT perform any gating,
# transformation, clustering, or statistical analysis. Instead, it takes already
# generated PNG plots from the refined output subfolders and combines them into
# summary panels for easier quality control and reporting.
#
# Expected input folder structure:
#
#   Base folder
#   ├── MMB 2D Plots
#   ├── DG 2D Plots
#   ├── MMB 1D Plots
#   └── DG 1D Plots
#
# Current overview outputs generated:
#
#   1) MMB_2D_Overview.png
#      - overview grid of all MMB FSC-H vs B525-H 2D scatter plots
#
#   2) DG_2D_Overview.png
#      - overview grid of all DG FSC-H vs B525-H 2D scatter plots
#
#   3) MMB_1D_Size_Overview.png
#      - overview grid of MMB FSC-H size distribution plots
#      - useful because MMB controls define the global MMB size window
#
#   4) DG_1D_Fluoro_Overview.png
#      - overview grid of DG B525-H fluorescence distribution plots
#      - useful because DG controls define the global DG fluorescence window
#
# Outputs intentionally NOT generated anymore:
#
#   - DG_1D_Size_Overview.png
#     Reason: DG controls are not used to define the global MMB size gate.
#
#   - MMB_1D_Fluoro_Overview.png
#     Reason: MMB controls are not used to define the global DG fluorescence gate.
#
# =============================================================================

from pathlib import Path
import math

import matplotlib
matplotlib.use("Agg")  # no GUI needed
import matplotlib.pyplot as plt
import matplotlib.image as mpimg


# =============================================================================
# Function: create overview PNG from selected PNG files
# =============================================================================

def make_overview_png_from_files(png_files, out_path: Path, title: str = ""):
    """
    Arrange given PNG files into a grid of subplots and save as a single image.

    Parameters
    ----------
    png_files : list[Path]
        List of PNG files to collate into one overview panel.

    out_path : Path
        Output path for the overview PNG.

    title : str
        Optional title placed above the overview figure.
    """
    png_files = sorted(png_files)

    if not png_files:
        print(f"⚠️ No PNG files provided for {out_path.name}, skipping.")
        return

    print(f"Creating overview with {len(png_files)} PNGs -> {out_path}")

    # Layout: up to 3 images per row
    n = len(png_files)
    ncols = min(3, n)
    nrows = math.ceil(n / ncols)

    # Size: roughly 4 inches per column, 3 inches per row
    fig, axes = plt.subplots(
        nrows,
        ncols,
        figsize=(4 * ncols, 3 * nrows),
        squeeze=False
    )

    for idx, png in enumerate(png_files):
        r = idx // ncols
        c = idx % ncols
        ax = axes[r][c]

        img = mpimg.imread(png)
        ax.imshow(img)
        ax.set_axis_off()

        # Use filename without extension as panel title
        ax.set_title(png.stem, fontsize=8)

    # Hide any unused axes
    for idx in range(len(png_files), nrows * ncols):
        r = idx // ncols
        c = idx % ncols
        axes[r][c].set_visible(False)

    if title:
        fig.suptitle(title, fontsize=12)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout(rect=(0, 0, 1, 0.96))  # leave room for suptitle
    fig.savefig(out_path, dpi=200)
    plt.close(fig)

    print(f"✔ Saved overview: {out_path}")


# =============================================================================
# Function: create overview PNG from all PNGs inside a folder
# =============================================================================

def make_overview_for_folder(folder: Path, out_path: Path, title: str = ""):
    """
    Convenience wrapper: make overview from all PNGs in a folder.
    """
    png_files = list(folder.glob("*.png"))

    if not png_files:
        print(f"⚠️ No PNG files found in {folder}, skipping.")
        return

    make_overview_png_from_files(png_files, out_path, title)


# =============================================================================
# Main
# =============================================================================

def main():
    # Base folder where the refined plots and subfolders live
    base = Path(
        r"D:\ICL MBE\Year 4\FYP\Software Automation\EC\Visual Flow Data\MMB and DG Controls Refined"
    )

    # Subfolders with 2D and 1D plots
    mmb_2d = base / "MMB 2D Plots"
    dg_2d = base / "DG 2D Plots"
    mmb_1d = base / "MMB 1D Plots"
    dg_1d = base / "DG 1D Plots"

    print(f"Base folder: {base}")
    print(f"MMB 2D folder: {mmb_2d}")
    print(f"DG 2D folder:  {dg_2d}")
    print(f"MMB 1D folder: {mmb_1d}")
    print(f"DG 1D folder:  {dg_1d}")

    # -------------------------------------------------------------------------
    # 2D overview panels
    # -------------------------------------------------------------------------
    mmb_2d_out = base / "MMB_2D_Overview.png"
    dg_2d_out = base / "DG_2D_Overview.png"

    make_overview_for_folder(
        folder=mmb_2d,
        out_path=mmb_2d_out,
        title="MMB 2D Plots"
    )

    make_overview_for_folder(
        folder=dg_2d,
        out_path=dg_2d_out,
        title="DG 2D Plots"
    )

    # -------------------------------------------------------------------------
    # 1D overview panel: DG fluorescence only
    # -------------------------------------------------------------------------
    dg_fluoro_files = [
        p for p in dg_1d.glob("*.png")
        if p.stem.endswith("Fluoro Distribution")
    ]

    dg_fluoro_out = base / "DG_1D_Fluoro_Overview.png"

    make_overview_png_from_files(
        png_files=dg_fluoro_files,
        out_path=dg_fluoro_out,
        title="DG 1D Fluoro Distributions"
    )

    # -------------------------------------------------------------------------
    # 1D overview panel: MMB size only
    # -------------------------------------------------------------------------
    mmb_size_files = [
        p for p in mmb_1d.glob("*.png")
        if p.stem.endswith("Size Distribution")
    ]

    mmb_size_out = base / "MMB_1D_Size_Overview.png"

    make_overview_png_from_files(
        png_files=mmb_size_files,
        out_path=mmb_size_out,
        title="MMB 1D Size Distributions"
    )

    print("\nDone.")


if __name__ == "__main__":
    main()